### ISSUE TITLE
Error when attempting wildcard certificate

### ISSUE THREAD

**Issue by Poyeyo** [obynio/certbot-plugin-gandi#11]
I get this:

`Performing the following challenges:`
`dns-01 challenge for example.com`
`Cleaning up challenges`
`Unable to find or delete the DNS TXT record: Unable to get base domain for "example.com"`
`An error occurred adding the DNS TXT record: Unable to get base domain for "example.com"`

When obtaining the certificate without wildcard, it all works fine.

**Comment by baloo** [comment]
@Poyeyo just curious, what was the issue?

**Comment by Poyeyo** [comment]
Wrong password in config file

**Comment by Deledrius** [comment]
I too am experiencing this issue, but only with some domains.  That would seem to preclude being a problem with the password (I assume you meant the API key?).

**Comment by obynio** [comment]
Are you sure you are not mismatching the user api key with the sharing id ?
If not you may missing rights to add TXT records to the domain.

**Comment by Deledrius** [comment]
I just tried it again and it appears to be working correctly now. 🤷 Thanks for this plugin!

**Comment by alexander-potemkin** [comment]
for those who will find this thread - the error seems to occur, indeed, when an API key is incorrect; in my specific case, I forgot to replace a placeholder for an API key at all :)

**Comment by phtnnz** [comment]
Run into this problem today with a fresh install of certbot on Ubuntu Server 22.04 LTS. Solution in a nutshell:
- DO NOT install the Ubuntu python3-certbot-dns-gandi with apt-get!
- Use pip install certbot-plugin-gandi instead
- Follow the instructions here on github ;-)

**Comment by obynio** [comment]
@phtnnz yes I've been trying to regain control of the Debian package but my email to the maintainer teams stays without replies.

**Comment by JukeboxRhino** [comment]
> Run into this problem today with a fresh install of certbot on Ubuntu Server 22.04 LTS. Solution in a nutshell:
> 
>     * DO NOT install the Ubuntu python3-certbot-dns-gandi with apt-get!
> 
>     * Use pip install certbot-plugin-gandi instead
> 
>     * Follow the instructions here on github ;-)

Thank you, this worked for me
