### ISSUE TITLE
Plugin don't work debian 10

### ISSUE THREAD

**Issue by lbopp42** [obynio/certbot-plugin-gandi#14]
Hello,
I am on debian 10 and have certbot 0.39.0.
When I do
`sudo certbot certonly -a certbot-plugin-gandi:dns \
--certbot-plugin-gandi:dns-credentials gandi.ini -d mydomain.fr \
--server https://acme-v02.api.letsencrypt.org/directory`
I got this error:
`usage:
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate.
certbot: error: unrecognized arguments: --certbot-plugin-gandi:dns-credentials gandi.ini`
Can I have any help please.
Best regards,
Lucas

**Comment by baloo** [comment]
How did you install the plugin? Because you're using sudo, this clears up the environment and my guess is that you do not have the plugin installed in root (or at least not visible from the environment you run with sudo)

**Comment by lbopp42** [comment]
Oh yes! You have right sorry. Thank you for your fast answer.
