### ISSUE TITLE
Gandi API changes

### ISSUE THREAD

**Issue by ZatsuneSakurako** [obynio/certbot-plugin-gandi#19]
"`There will be no future developments on this API, as we are merging to our new REST api endpoint, which is documented at https://api.gandi.net/docs/livedns/`"

Do you plan to support the new api ?

**Comment by obynio** [comment]
I was not aware a new API was here. I plan to support it once it's out of beta. The endpoints seems to have the same behaviour so it won't be a huge deal supporting it.

**Comment by ZatsuneSakurako** [comment]
I can leave this opened, so you can close it when the api will be out of beta ?

**Comment by baloo** [comment]
If I read the code correctly, that should work out of the box by just switching the base url.

I'm a developer on the gandi dns platform, please hit me up if you have any issue with it.

**Comment by obynio** [comment]
@ZatsuneNoMokou yup, let's keep this open until we switch to the new API.

**Comment by JuliaScythe** [comment]
As of 2021-11-30, the new API is stable, so it's probably safe to switch the base URL
