### ISSUE TITLE
certbot: error: unrecognized arguments: --certbot-plugin-gandi:dns-credentials gandi.ini

### ISSUE THREAD

**Issue by KyronNextLevel** [obynio/certbot-plugin-gandi#20]
Hello.
I'm trying to use your plugin but sadly I got a unrecognized arguments error...

certbot certonly -a certbot-plugin-gandi:dns --certbot-plugin-gandi:dns-credentials gandi.ini -d [domain]  --dry-run
usage: 
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate. 
certbot: error: unrecognized arguments: --certbot-plugin-gandi:dns-credentials gandi.ini

Sadly, I see nothing helpful in letsencypt logs...

Too bad, this plugin seems great.

I'm using Centos 7.8.2003
Certbot 1.7.0
certbot-plugin-gandi 1.2.5 from pip3

**Comment by obynio** [comment]
Hello, the plugin is working as expected, so I would guess that may be an issue with your python environment or with certbot failing to detect the installed plugin (permission issues etc...).

Maybe try with another provider if you can to see if you have the same issue.
https://certbot.eff.org/docs/using.html?highlight=dn#dns-plugins
