### ISSUE TITLE
add parameter like --dns-gandi-propagation-seconds

### ISSUE THREAD

**Issue by tomamplius** [obynio/certbot-plugin-gandi#21]
Some time i need to use --debug-challenges to wait more than 10 second for propagation.
All plugin's are parameter like --dns-<plugin>-propagation-seconds
Can you add this parameter?

Regards,

**Comment by obynio** [comment]
Coud you provide an example plugin with this option ?

**Comment by tomamplius** [comment]
Thank for your answer

The number of seconds to wait for DNS to propagate  before asking the ACME server to verify the DNS record. (default: 90)
It's juste a sleep command


In cerbot documentation (https://certbot.eff.org/docs/using.html) at the end in the plugin part you have :
--dns-cloudflare-propagation-seconds
--dns-cloudxns-propagation-seconds
 --dns-dnsimple-propagation-seconds
  --dns-gehirn-propagation-seconds 
 --dns-google-propagation-seconds 
  --dns-nsone-propagation-seconds
--dns-rfc2136-propagation-seconds
  --dns-route53-propagation-seconds 
 --dns-sakuracloud-propagation-seconds

**Comment by obynio** [comment]
This plugin inherit `dns_common.DNSAuthenticator` [here](https://github.com/obynio/certbot-plugin-gandi/blob/master/certbot_plugin_gandi/main.py#L29) and supercharge its `add_parser_arguments` method from [there](https://github.com/certbot/certbot/blob/master/certbot/certbot/plugins/dns_common.py#L33) so the option should be available. There is nothing I can do on my side as the propagation sleep is done [inside certbot](https://github.com/certbot/certbot/blob/master/certbot/certbot/plugins/dns_common.py#L65).

Try with `--certbot-plugin-gandi:dns-propagation-seconds`.

**Comment by tomamplius** [comment]
Thanks, it's work.

![image](https://user-images.githubusercontent.com/6951820/101499474-9c36fd00-396d-11eb-834c-35579d66fd9c.png)

**Comment by glyph** [comment]
Trying this just now, it seems like the parameter is actually `--dns-gandi-propagation-seconds=`?

**Comment by tomamplius** [comment]
I work in other company and i hav'nt gandi domain currently.
