### ISSUE TITLE
Plugin removed in future version ?

### ISSUE THREAD

**Issue by AntoineDavidSupersoniks** [obynio/certbot-plugin-gandi#23]
Hi,

With certbot 1.10.1 i've this warning :

Plugin legacy name certbot-plugin-gandi:dns may be removed in a future version. Please use dns instead.

What is DNS plugin ?

Cordialy

**Comment by bourgeoa** [comment]
I suppose this relates to the following : 
There will be no future developments on this API, as we are merging to our new REST api endpoint, which is documented at https://api.gandi.net/docs/livedns/

**Comment by alexzorin** [comment]
The deprecation warning refers to the "prefix" part of the plugin entrypoint when you pass it on the Certbot CLI. More information at https://github.com/certbot/certbot/pull/8131.

Currently, with the prefix:

    --certbot-plugin-gandi:dns-credentials

Afterwards, without the prefix:

    --dns-credentials

Unfortunately in this case of this project, using the generic `dns` name doesn't mesh too great with the deprecation of the prefix. 

cc @obynio, just so you are aware of the potential future issue.

**Comment by aearil** [comment]
Well, it seems that `certbot 1.11.0` already removed the old version, right now when I try to renew my wildcard, get the following:

```
$ sudo /usr/bin/certbot renew -q -a 'certbot-plugin-gandi:dns' '--certbot-plugin-gandi:dns-credentials' /etc/letsencrypt/gandi.ini --server 'https://acme-v02.api.letsencrypt.org/directory'

usage:   certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...
Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate. 
certbot: error: unrecognized arguments: --certbot-plugin-gandi:dns-credentials /etc/letsencrypt/gandi.ini
```

Is there a workaround?

@alexzorin, you say that
> Unfortunately in this case of this project, using the generic dns name doesn't mesh too great with the deprecation of the prefix.
Does that mean this is unfixable, or is there a way I can help?

**Comment by AntoineDavidSupersoniks** [comment]
Currently I am using the following instructions and I have no problems apart from this anxiety-provoking warning

`--authenticator certbot-plugin-gandi:dns --certbot-plugin-gandi:dns-credentials /root/.secrets/gandi.ini`

**Comment by JulienPalard** [comment]
Looks like it works without the prefix:

    --authenticator dns --dns-credentials /etc/gandi.ini

... hum, doing a PR to explain that and migrate to a better name.

**Comment by JulienPalard** [comment]
In #24 I propose we use `--authenticator dns-gandi` and `--dns-gandi-credentials`, while keeping compat with the prefixed notation during a transition period (say up to cerbot completly drop it).

**Comment by AntoineDavidSupersoniks** [comment]
Awesome !

**Comment by obynio** [comment]
Hello, a new version was release to add these changes

**Comment by AntoineDavidSupersoniks** [comment]
HI with a pip upgrade i don't have the new release :(

```sh
pip3 install certbot-plugin-gandi --upgrade
```


i'v the following error :
```sh
root@65df9fa35a70:~# certbot certonly --authenticator dns-gandi --dns-gandi-credentials /root/.secrets/certbot/gandi-supersoniks.ini -d decoflorale.com
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-gandi, Installer None
Requesting a certificate for decoflorale.com
Performing the following challenges:
dns-01 challenge for decoflorale.com
Cleaning up challenges
Missing property in credentials configuration file /root/.secrets/certbot/gandi-supersoniks.ini:
 * Property "dns_gandi_api_key" not found (should be API key for Gandi account).
```
file : gandi-supersoniks.ini:
```sh
# live dns v5 api key
certbot_plugin_gandi:dns_api_key=xxxxxxxxxxxxxxxxxxxxxxxxxxxx

# new ???
dns_gandi_api_key:dns_api_key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# optional organization id, remove it if not used
# certbot_plugin_gandi:dns_sharing_id=SHARINGID
```

**Comment by obynio** [comment]
@AntoineDavidSupersoniks please take a look at this #25
