### ISSUE TITLE
Instructions typos ?

### ISSUE THREAD

**Issue by padawan** [obynio/certbot-plugin-gandi#25]
Hi,

I think there is a typo in this command:

`certbot certonly --authenticator dns-gandi --dns-gandi-credentials /etc/letsencrypt/gandi/gandi.ini gandi.ini -d domain.com`

the `--dns-gandi-credentials` option should be followed by only one file path (there are two pointing to the gandi.ini file).

Also, when running the plugin, using /root/gandi.ini as configuration, I get the following error:

```
Missing property in credentials configuration file /root/gandi.ini:
 * Property "dns_gandi_api_key" not found (should be API key for Gandi account).
```

It works with this:
```
# live dns v5 api key
dns_gandi_api_key=<key>
```

**Comment by obynio** [comment]
Indeed you're right, I will correct this right now. Thanks for noticing it !
