### ISSUE TITLE
error: unrecognized arguments: --dns-gandi-credentials 

### ISSUE THREAD

**Issue by badroum** [obynio/certbot-plugin-gandi#27]
Hello, I have this error
I tried with the old configuration of the pluging but without better result
my certbot version is 1.13.0

can someone help me?
 
sudo certbot certonly --authenticator dns-gandi --dns-gandi-credentials /opt/certbot/gandi.ini -d XXX.yyy -d \*.XXX.yyy --server https://acme-v02.api.letsencrypt.org/directory
usage:
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate.
certbot: error: unrecognized arguments: --dns-gandi-credentials /opt/certbot/gandi.ini

**Comment by obynio** [comment]
* What version of `certbot-plugin-gandi` are you using ?
* From what source did you installed `certbot-plugin-gandi` ?
* What platform and python version are you using ?

You need to use a `certbot-plugin-gandi>=1.3.2` and `certbot>=1.7.0`
For everyone else do not hesitate to drop a comment if you're affected by the issue.

**Comment by obynio** [comment]
You need to use a `certbot-plugin-gandi>=1.3.2` and `certbot>=1.7.0`

**Comment by badroum** [comment]
Hello,

thank you for your answer, here are my versions
"Raspbian GNU/Linux 10 (buster)"
Python 2.7.16
Python 3.7.3
certbot              1.11.0
certbot-plugin-gandi 1.3.2

**Comment by obynio** [comment]
Hello,

I just tested on a Debian Buster using certbot v1.13 and nothing to report everything was running perfectly.
You certbot installation might be messed up, can you please run the following commands and paste me here the output.

* `which certbot` to check if certbot is not "shadowed" by another older installation
* `certbot --version` to check which certbot is currently running
* `certbot plugins` to see the entrypoints of currently installed plugins
* `sudo pip list | grep certbot` to check if certbot was installed using python 2
* `sudo pip3 list | grep certbot` to check if certbot was installed using python 3
* `sudo dpkg -l | grep certbot` to check if certbot was installed using apt

If that's not already the case, please instal `certbot` using pip3 rather than apt to get the most up-to-date version.

**Comment by badroum** [comment]
pi@raspberrypi:~ $ certbot --version
certbot 1.11.0
pi@raspberrypi:~ $ certbot plugins

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
* dns
Description: Obtain certificates using a DNS TXT record (if you are using Gandi
for DNS).
Interfaces: IAuthenticator, IPlugin
Entry point: dns = certbot_plugin_gandi.main:Authenticator

* dns-gandi
Description: Obtain certificates using a DNS TXT record (if you are using Gandi
for DNS).
Interfaces: IAuthenticator, IPlugin
Entry point: dns-gandi = certbot_plugin_gandi.main:Authenticator

* standalone
Description: Spin up a temporary webserver
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = certbot._internal.plugins.standalone:Authenticator

* webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
pi@raspberrypi:~ $ sudo pip list | grep certbot
pi@raspberrypi:~ $ sudo pip3 list | grep certbot
certbot           0.31.0
pi@raspberrypi:~ $ sudo dpkg -l | grep certbot
rc  certbot                              0.31.0-1+deb10u1                      all          automatically configure HTTPS using Let's Encrypt
ii  python3-certbot                      0.31.0-1+deb10u1                      all          main library for certbot
pi@raspberrypi:~ $

**Comment by obynio** [comment]
I don't understand why it does not works as expected. Entrypoints are correct but the plugin isn't detected by certbot. 
Using the legacy entrypoints may work, you should give it a try.

https://github.com/obynio/certbot-plugin-gandi#legacy-prefix-based-configuration-for-certbot170

I also see you're installing certbot using APT (certbot 0.31.0), I would advise to clean your certbot installation and install certbot using pip to get the latest version.
