### ISSUE TITLE
Systemd renewal timer fails with error "Namespace' object has no attribute 'dns_gandi_credentials'"

### ISSUE THREAD

**Issue by se1by** [obynio/certbot-plugin-gandi#37]
As the title says. The automatic renewal (without setting up a cronjob) fails with said message.
Editing `/etc/letsencrypt/renewal/domain.tld.conf` by hand, replacing `dns_gandi_credentials` with `dns-gandi-credentials` fixes this.
I can't tell yet if automatic renewal does work, but that change got rid of the error.

Versions:
certbot              1.31.0
certbot-plugin-gandi 1.4.0

Both installed with pip.

**Comment by obynio** [comment]
Hello, which distribution & release are you using ? As far as I know python packages installed with pip do not have any interaction with SystemD, so this seems very weird. Is it the SystemD service from certbot ?

**Comment by HLFH** [comment]
Shall this be closed @obynio as you did not get any reply regarding the systemd unit used by @se1by. 

`certbot` may be updated here.
And despite what is being said, renewal conf. in `/etc/letsencrypt/renewal/*.conf` should have underscores.
Documentation of certbot should be clarified regarding renewal confiiguration files as seen in https://github.com/certbot/certbot/issues/5935 and in this comment: https://github.com/certbot/certbot/issues/5935#issuecomment-780544995.
