### ISSUE TITLE
cron expression wrong?

### ISSUE THREAD

**Issue by ayedo** [obynio/certbot-plugin-gandi#8]
Hi!

First of all, thanks for your work on this plugin.

I've entered the cron expression provided in the README into a cron verifier:

https://crontab.guru/#*_1_*_*_1

It claims to run 
“At every minute past hour 1 on Monday.”

Should't it be something like: "0 0 * * 0" instead?

**Comment by obynio** [comment]
Not a big deal. It just mean it will run at 01:00:00 every Monday.
I just replaced it by yours which seems more meaningful.
